name: Build ShareX-slim

on:
  push:
    branches:
      - "**"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "**/*.md"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build (${{ matrix.configuration }}, ${{ matrix.platform }})
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        configuration: [Release, Debug]
        platform: [x64, ARM64]

    env:
      SOLUTION_FILE_PATH: ShareX.Slim.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Set RUNTIME_ID
        run: |
          $platform = if ("${{ matrix.platform }}" -eq "ARM64") { "arm64" } else { "x64" }
          echo "PLATFORM=$platform" >> $env:GITHUB_ENV
          echo "RUNTIME_ID=win-$platform" >> $env:GITHUB_ENV

      - name: Restore NuGet packages
        run: dotnet restore --runtime "${{ env.RUNTIME_ID }}" "${{ env.SOLUTION_FILE_PATH }}"

      - name: Build
        run: >
          dotnet build --no-restore
          --configuration "${{ matrix.configuration }}"
          -p:Platform="${{ matrix.platform }}"
          --self-contained true /m:1
          "${{ env.SOLUTION_FILE_PATH }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ShareX-slim-${{ matrix.configuration }}-${{ env.PLATFORM }}
          path: ShareX/bin/${{ matrix.configuration }}/${{ env.RUNTIME_ID }}/
